version: '3'

services:
  # MySQL
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d
    # security_opt:
    #   - seccomp:uncofined

  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    ports:
      - 8080:80